$schema: "http://json-schema.org/draft-06/schema#"

definitions:
  Topic:
    type: object
    properties:
      name:
        type: string
      format:
        type: string

    Parameter:
      type: object
      properties:
        name:
          type: string

  Node:
    type: object
    properties:
      name:
        type: string
      package:
        type: string
      source:
        type: string
      publishes:
        type: array
        items:
          $ref: '#/definitions/Topic'
        default: []
      subscribes:
        type: array
        items:
          $ref: '#/definitions/Topic'
        default: []
      parameters:
        type: array
        items:
          $ref: '#/definitions/Parameter'
        default: []

type: object
properties:
  nodes:
    type: array
    items:
      $ref: '#/definitions/Node'
    default: []
