$schema: "http://json-schema.org/draft-06/schema#"

definitions:
  Package:
    type: object
    properties:
      name:
        type: string

      nodes:
        type: array
        items:
          $ref: '#/definitions/Node'
        default: []

      services:
        type: array
        items:
          $ref: '#/definitions/Service'
        default: []

      parameters:
        type: object
        properties:
          reads:
            type: array
            items:
              $ref: '#/definitions/ParamRead'
            default: []
          writes:
            type: array
            items:
              $ref: '#/definitions/ParamWrite'
            default: []

      subscribers:
        type: array
        items:
          $ref: '#/definitions/Subscriber'
        default: []

      publishers:
        type: array
        items:
          $ref: '#/definitions/Publisher'
        default: []

  ParamRead:
    type: object
    properties:
      name:
        type: string
        required: yes
      location:
        $ref: '#/definitions/Location'
      default:
        oneOf:
          - type: int
          - type: string
          - type: bool
          - type: float

  ParamWrite:
    type: object
    properties:
      name:
        type: string
        required: yes
      location:
        $ref: '#/definitions/Location'

  Subscriber:
    type: object
    properties:
      name:
        type: string
        required: yes
      format:
        type: string
        required: yes
      location:
        $ref: '#/definitions/Location'
        required: yes

  Publisher:
    type: object
    properties:
      name:
        type: string
        required: yes
      format:
        type: string
        required: yes
      location:
        $ref: '#/definitions/Location'

  Location:
    type: string
    required: yes

  Node:
    type: object
    properties:
      name:
        type: string
        required: yes
      location:
        $ref: '#/definitions/Location'

type: object
properties:
  packages:
    type: array
    items:
      $ref: '#/definitions/Package'
    default: []
